# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.synced_folder "data/", "/vagrant/vagrant_data", disabled: true
        
  config.proxy.http     = "http://192.168.26.33:87"
  config.proxy.https    = "http://192.168.26.33:87"
  config.proxy.no_proxy = "localhost,127.0.0.1"
  
   config.vm.provider :virtualbox do |vb|
      vb.memory = "512"
  end
  
  config.vm.define "client" do |client|
    client.vm.hostname = "client.local"
    client.vm.network "private_network", ip: "192.168.10.10"
  end

  config.vm.define "lb01" do |lb01|
    lb01.vm.hostname = "lb01.local"
    lb01.vm.network "private_network", ip: "192.168.10.11"
  end

  config.vm.define "lb02" do |lb02|
    lb02.vm.hostname = "lb02.local"
    lb02.vm.network "private_network", ip: "192.168.10.12"
  end

  config.vm.define "nginx01" do |nginx01|
    nginx01.vm.hostname = "nginx01.local"
    nginx01.vm.network "private_network", ip: "192.168.10.13"
  end

  config.vm.define "nginx02" do |nginx02|
    nginx02.vm.hostname = "nginx02.local"
    nginx02.vm.network "private_network", ip: "192.168.10.14"
  end

end
